# Generated by Django 3.1.2 on 2020-11-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_item_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
