# Generated by Django 3.1.2 on 2020-12-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201207_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='groupnumber',
            new_name='family_number',
        ),
    ]
