# Generated by Django 3.1.2 on 2020-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201208_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tmp_group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
