# Generated by Django 3.1.2 on 2020-11-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_item_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='complete',
        ),
    ]
