# Generated by Django 3.1.4 on 2020-12-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_myfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='myfield',
        ),
    ]
