# Generated by Django 3.1.4 on 2020-12-18 16:04

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_myfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
