# Generated by Django 3.1.2 on 2020-11-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20201127_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupList',
            new_name='GroupVisitor',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='grouplist',
            new_name='groupvisitor',
        ),
    ]
