# Generated by Django 3.1.2 on 2020-11-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20201129_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupVisitor',
            new_name='VisitorGroup',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='groupvisitor',
            new_name='visitorgroup',
        ),
    ]
