# Generated by Django 3.1.2 on 2020-11-30 21:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_auto_20201130_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Visitor',
        ),
    ]
