# Generated by Django 3.1.2 on 2020-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20201130_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervallStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
