# Generated by Django 3.1.2 on 2020-12-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_churchdayvisitor_churchdayvisitorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdayvisitorgroup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
