# Generated by Django 3.1.2 on 2020-12-01 00:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_churchdayvisitorgroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroup',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
