# Generated by Django 3.1.2 on 2020-12-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20201201_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitorgroup',
            name='data',
        ),
        migrations.DeleteModel(
            name='ChurchDayVisitor',
        ),
    ]
