# Generated by Django 3.1.2 on 2020-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_auto_20201201_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchdayvisitorgroup',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
