# Generated by Django 3.1.2 on 2020-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20201201_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdayvisitorgroup',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='churchdayvisitorgroup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
