# Generated by Django 3.1.2 on 2020-12-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_churchdayvisitorgroup_visitorgroup_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
