# Generated by Django 3.1.2 on 2020-12-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_churchdayvisitorgroup_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchdayvisitorgroup',
            name='author',
        ),
    ]
