# Generated by Django 3.1.2 on 2020-12-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_remove_churchdayvisitorgroup_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churchdayvisitorgroup',
            old_name='data',
            new_name='visitor_list',
        ),
    ]
