# Generated by Django 3.1.2 on 2020-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_auto_20201202_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervallDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IntervallStart',
        ),
    ]
