# Generated by Django 3.1.2 on 2020-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_auto_20201202_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdayvisitorgroup',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='churchdayvisitorgroup',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='churchdayvisitorgroup',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
