# Generated by Django 3.1.2 on 2020-12-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_auto_20201204_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchdayvisitorgroup',
            name='day',
        ),
        migrations.RemoveField(
            model_name='churchdayvisitorgroup',
            name='month',
        ),
        migrations.RemoveField(
            model_name='churchdayvisitorgroup',
            name='year',
        ),
    ]
