# Generated by Django 3.1.2 on 2020-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_auto_20201204_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalldate',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
