# Generated by Django 3.1.2 on 2020-12-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_visitor_groupnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='Groupnumber',
            new_name='groupnumber',
        ),
    ]
