# Generated by Django 3.1.2 on 2020-12-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_auto_20201208_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='groupnumber',
            new_name='family_number',
        ),
    ]
