# Generated by Django 3.1.2 on 2020-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_auto_20201208_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroup',
            name='allow_group_login',
            field=models.BooleanField(null=True),
        ),
    ]
